name: Deploy Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: build and deploy app
    runs-on: ubuntu-22.04
    environment: production

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Remove old distribution from remote host
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 'rm -rf ${{ secrets.REMOTE_DIST_PATH }}dist'

      - name: Upload new distribution to remote host
        run: scp -r dist ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.REMOTE_DIST_PATH }}